### ISSUE TITLE
suggestion: Correct repository description

### ISSUE THREAD

**Issue by moreal** [ketion-so/go-notion#18]
The description of this repository is *'SDK for Notion.io API'*. But the [Notion](https://www.notion.so)'s official url is *https://www.notion.so*. So, how about replacing it into *notion.so* or *Notion*? Or please tell me if there is other intention. Thanks 🙏🏻

**Comment by KeisukeYamashita** [comment]
@moreal  Thank you for raising an issue.
Exactly!! 

Just fixed 👍 

![image](https://user-images.githubusercontent.com/23056537/118357644-3bfc5500-b5b6-11eb-82d8-d077302183db.png)
